name: Check GitHub SCIM Drifts
permissions:
  contents: read
on:
  workflow_dispatch:

  schedule:
    # Runs on every monday at 13:00 UTC
    #
    #        ┌────────────── minute
    #        │  ┌──────────── hour
    #        │  │ ┌────────── day (month)
    #        │  │ │ ┌──────── month
    #        │  │ │ │ ┌────── day (week)
    - cron: '0 13 * * 1'

jobs:
  check_scim_drifts:
    runs-on: ubuntu-24.04

    steps:
      - name: Check GitHub SCIM Drifts
        uses: tentwentyone/github-org-members-verify-scim-identities@v1.0.2
        with:
          gh_app_id: ${{ secrets.GH_APP_ORG_READ_ID }}
          gh_pem_key: ${{ secrets.GH_APP_ORG_READ_PEM_KEY }}
          gh_install_id: ${{ secrets.GH_APP_ORG_READ_INSTALL_ID }}
